#!/bin/sh
if [ "$1" = "remove" -o "$1" = "abort-install" -o "$1" = "disappear" ] \
    && [ -n "$(dpkg-divert --list amneziawg)" ]; then
  dpkg-divert --package amneziawg  --rename --remove \
              /opt/vyatta/share/perl5/Vyatta/Interface.pm
  dpkg-divert --package amneziawg  --rename --remove \
              /opt/vyatta/share/vyatta-cfg/templates/firewall/options/mss-clamp/interface-type/node.def
  dpkg-divert --package amneziawg  --rename --remove \
              /opt/vyatta/share/vyatta-cfg/templates/firewall/options/mss-clamp6/interface-type/node.def
fi
